import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface CandidateData {
  name: string;
  email: string;
  position: string;
  interviewDate: string;
  invitedDate?: string;
  status: 'completed' | 'in-progress' | 'scheduled';
  score: number;
  interviewType: 'voice' | 'video' | 'both';
  experienceLevel: 'fresher' | 'mid' | 'senior';
  confidenceScore?: number;
  technicalDepth?: number;
  communication?: number;
  // Enhanced interview data
  resumeData?: {
    skills: string[];
    experience: string[];
    education: string[];
    projects: string[];
    summary: string;
    workExperience: Array<{
      company: string;
      position: string;
      duration: string;
      description: string;
    }>;
    totalExperience: number;
  };
  interviewTranscript?: string;
  questionsAsked?: Array<{
    question: string;
    answer: string;
    score?: number;
    feedback?: string;
  }>;
  codingChallenges?: Array<{
    problem: string;
    solution: string;
    testsPassed: number;
    totalTests: number;
    executionTime: number;
  }>;
  aiInsights?: {
    strengths: string[];
    weaknesses: string[];
    recommendation: string;
    culturalFit: number;
    technicalFit: number;
  };
  interviewDuration?: number;
}

const addHeader = (doc: jsPDF, title: string) => {
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('HIRE MIND', 105, 20, { align: 'center' });
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 105, 30, { align: 'center' });
  doc.setTextColor(0, 0, 0);
};

const addPageFooter = (doc: jsPDF, pageNum: number, totalPages: number) => {
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(
    `Generated by Hire Mind AI | ${new Date().toLocaleDateString()} | Page ${pageNum} of ${totalPages}`,
    105, 285, { align: 'center' }
  );
};

const splitTextToLines = (text: string, maxWidth: number, doc: jsPDF): string[] => {
  return doc.splitTextToSize(text, maxWidth);
};

export const generateCandidatePDF = (candidate: CandidateData) => {
  const doc = new jsPDF();
  let yPos = 55;
  
  // Page 1: Overview & Basic Info
  addHeader(doc, 'AI-Powered Interview Analysis Report');
  
  // Executive Summary Box
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(20, yPos, 170, 35, 3, 3, 'F');
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 25, yPos + 12);
  
  if (candidate.status === 'completed') {
    const recommendation = candidate.score >= 80 ? 'STRONGLY RECOMMEND' : 
                          candidate.score >= 65 ? 'RECOMMEND' : 
                          candidate.score >= 50 ? 'CONSIDER' : 'NOT RECOMMENDED';
    
    const color = candidate.score >= 80 ? [22, 163, 74] : 
                  candidate.score >= 65 ? [59, 130, 246] :
                  candidate.score >= 50 ? [245, 158, 11] : [239, 68, 68];
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Overall Score: ${candidate.score}%`, 25, yPos + 22);
    
    doc.setTextColor(color[0], color[1], color[2]);
    doc.setFont('helvetica', 'bold');
    doc.text(`Recommendation: ${recommendation}`, 25, yPos + 30);
    doc.setTextColor(0, 0, 0);
  } else {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Status: ${candidate.status.toUpperCase()}`, 25, yPos + 22);
  }
  
  yPos += 45;
  
  // Candidate Basic Information
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Candidate Information', 20, yPos);
  yPos += 10;
  
  const basicInfo = [
    ['Name:', candidate.name],
    ['Email:', candidate.email],
    ['Position Applied:', candidate.position],
    ['Interview Type:', candidate.interviewType.toUpperCase()],
    ['Experience Level:', candidate.experienceLevel.charAt(0).toUpperCase() + candidate.experienceLevel.slice(1)],
    ['Interview Date:', candidate.interviewDate],
    ['Duration:', candidate.interviewDuration ? `${candidate.interviewDuration} minutes` : 'N/A'],
    ['Status:', candidate.status.toUpperCase()]
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [],
    body: basicInfo,
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 50 },
      1: { cellWidth: 120 }
    }
  });
  
  // Resume Analysis Section
  if (candidate.resumeData) {
    yPos = (doc as any).lastAutoTable.finalY + 15;
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Resume Analysis', 20, yPos);
    yPos += 10;
    
    // Professional Summary
    if (candidate.resumeData.summary) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Professional Summary:', 20, yPos);
      yPos += 8;
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const summaryLines = splitTextToLines(candidate.resumeData.summary, 170, doc);
      summaryLines.forEach((line, index) => {
        if (yPos > 270) {
          doc.addPage();
          addHeader(doc, 'Interview Analysis Report - Resume Details');
          yPos = 55;
        }
        doc.text(line, 20, yPos + (index * 6));
      });
      yPos += summaryLines.length * 6 + 10;
    }
    
    // Work Experience
    if (candidate.resumeData.workExperience && candidate.resumeData.workExperience.length > 0) {
      if (yPos > 240) {
        doc.addPage();
        addHeader(doc, 'Interview Analysis Report - Work Experience');
        yPos = 55;
      }
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Work Experience:', 20, yPos);
      yPos += 8;
      
      candidate.resumeData.workExperience.slice(0, 3).forEach((job, index) => {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(`${job.position} at ${job.company}`, 20, yPos);
        
        doc.setFont('helvetica', 'normal');
        doc.text(`(${job.duration})`, 20, yPos + 6);
        
        if (job.description) {
          const descLines = splitTextToLines(job.description.substring(0, 200) + '...', 160, doc);
          descLines.slice(0, 2).forEach((line, lineIndex) => {
            doc.text(line, 20, yPos + 12 + (lineIndex * 5));
          });
        }
        
        yPos += 22;
        
        if (yPos > 260) {
          doc.addPage();
          addHeader(doc, 'Interview Analysis Report - Work Experience');
          yPos = 55;
        }
      });
      
      yPos += 5;
    }
    
    // Skills Analysis
    if (candidate.resumeData.skills && candidate.resumeData.skills.length > 0) {
      if (yPos > 250) {
        doc.addPage();
        addHeader(doc, 'Interview Analysis Report - Skills');
        yPos = 55;
      }
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Technical Skills:', 20, yPos);
      yPos += 8;
      
      // Group skills into rows
      const skillsPerRow = 3;
      const skillRows: string[][] = [];
      for (let i = 0; i < candidate.resumeData.skills.length; i += skillsPerRow) {
        skillRows.push(candidate.resumeData.skills.slice(i, i + skillsPerRow));
      }
      
      autoTable(doc, {
        startY: yPos,
        head: [],
        body: skillRows.slice(0, 8), // Limit to first 8 rows
        theme: 'grid',
        styles: { fontSize: 9, cellPadding: 4, halign: 'center' },
        columnStyles: {
          0: { cellWidth: 56.67 },
          1: { cellWidth: 56.67 },
          2: { cellWidth: 56.67 }
        }
      });
      
      yPos = (doc as any).lastAutoTable.finalY + 15;
    }
  }
  
  // Start new page for performance metrics
  if (candidate.status === 'completed') {
    doc.addPage();
    addHeader(doc, 'Performance Analysis & Results');
    yPos = 55;
    
    // Overall Score Display
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(20, yPos, 170, 35, 3, 3, 'F');
    
    doc.setFontSize(18);
    doc.setTextColor(22, 163, 74);
    doc.setFont('helvetica', 'bold');
    doc.text('Overall Interview Score', 25, yPos + 15);
    
    doc.setFontSize(32);
    const scoreColor = candidate.score >= 80 ? [22, 163, 74] : 
                       candidate.score >= 60 ? [245, 158, 11] : [239, 68, 68];
    doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.text(`${candidate.score}%`, 165, yPos + 25, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    
    yPos += 45;
    
    // Detailed Performance Metrics
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Performance Breakdown', 20, yPos);
    yPos += 10;
    
    const performanceMetrics = [
      ['Communication Skills', `${candidate.communication || 0}%`],
      ['Technical Knowledge', `${candidate.technicalDepth || 0}%`],
      ['Confidence Level', `${candidate.confidenceScore || 0}%`],
      ['Cultural Fit', `${candidate.aiInsights?.culturalFit || 0}%`],
      ['Technical Fit', `${candidate.aiInsights?.technicalFit || 0}%`]
    ];
    
    autoTable(doc, {
      startY: yPos,
      head: [['Evaluation Criteria', 'Score']],
      body: performanceMetrics,
      theme: 'striped',
      headStyles: { fillColor: [79, 70, 229], textColor: 255 },
      styles: { fontSize: 11, cellPadding: 6 },
      columnStyles: {
        0: { cellWidth: 120, fontStyle: 'bold' },
        1: { cellWidth: 50, halign: 'center', fontStyle: 'bold' }
      }
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 15;
    
    // AI Insights
    if (candidate.aiInsights) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('AI Analysis & Insights', 20, yPos);
      yPos += 10;
      
      // Strengths
      if (candidate.aiInsights.strengths && candidate.aiInsights.strengths.length > 0) {
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Key Strengths:', 20, yPos);
        yPos += 8;
        
        candidate.aiInsights.strengths.forEach((strength, index) => {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          const strengthLines = splitTextToLines(`• ${strength}`, 160, doc);
          strengthLines.forEach((line, lineIndex) => {
            doc.text(line, 25, yPos + (lineIndex * 5));
          });
          yPos += strengthLines.length * 5 + 2;
        });
        
        yPos += 5;
      }
      
      // Areas for improvement
      if (candidate.aiInsights.weaknesses && candidate.aiInsights.weaknesses.length > 0) {
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Areas for Improvement:', 20, yPos);
        yPos += 8;
        
        candidate.aiInsights.weaknesses.forEach((weakness, index) => {
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          const weaknessLines = splitTextToLines(`• ${weakness}`, 160, doc);
          weaknessLines.forEach((line, lineIndex) => {
            doc.text(line, 25, yPos + (lineIndex * 5));
          });
          yPos += weaknessLines.length * 5 + 2;
        });
        
        yPos += 5;
      }
      
      // Recommendation
      if (candidate.aiInsights.recommendation) {
        if (yPos > 240) {
          doc.addPage();
          addHeader(doc, 'AI Recommendation');
          yPos = 55;
        }
        
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Final Recommendation:', 20, yPos);
        yPos += 8;
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        const recommendationLines = splitTextToLines(candidate.aiInsights.recommendation, 160, doc);
        recommendationLines.forEach((line, index) => {
          doc.text(line, 20, yPos + (index * 5));
        });
        yPos += recommendationLines.length * 5 + 10;
      }
    }
  }
  
  // Coding Challenges Section
  if (candidate.codingChallenges && candidate.codingChallenges.length > 0) {
    doc.addPage();
    addHeader(doc, 'Technical Assessment Results');
    yPos = 55;
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Coding Challenge Performance', 20, yPos);
    yPos += 15;
    
    candidate.codingChallenges.forEach((challenge, index) => {
      if (yPos > 240) {
        doc.addPage();
        addHeader(doc, 'Technical Assessment Results');
        yPos = 55;
      }
      
      // Challenge header
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`Challenge ${index + 1}:`, 20, yPos);
      yPos += 8;
      
      // Problem description
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const problemLines = splitTextToLines(challenge.problem.substring(0, 200) + '...', 160, doc);
      problemLines.slice(0, 3).forEach((line, lineIndex) => {
        doc.text(line, 20, yPos + (lineIndex * 5));
      });
      yPos += problemLines.length * 5 + 5;
      
      // Results
      const passPercentage = (challenge.testsPassed / challenge.totalTests) * 100;
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`Results: ${challenge.testsPassed}/${challenge.totalTests} tests passed (${passPercentage.toFixed(1)}%)`, 20, yPos);
      doc.text(`Execution Time: ${challenge.executionTime}ms`, 20, yPos + 6);
      
      yPos += 20;
    });
  }
  
  // Interview Questions & Answers (if available)
  if (candidate.questionsAsked && candidate.questionsAsked.length > 0) {
    doc.addPage();
    addHeader(doc, 'Interview Q&A Summary');
    yPos = 55;
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Interview Questions & Responses', 20, yPos);
    yPos += 15;
    
    candidate.questionsAsked.slice(0, 5).forEach((qa, index) => {
      if (yPos > 200) {
        doc.addPage();
        addHeader(doc, 'Interview Q&A Summary');
        yPos = 55;
      }
      
      // Question
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`Q${index + 1}:`, 20, yPos);
      
      doc.setFont('helvetica', 'normal');
      const questionLines = splitTextToLines(qa.question, 150, doc);
      questionLines.forEach((line, lineIndex) => {
        doc.text(line, 30, yPos + (lineIndex * 5));
      });
      yPos += questionLines.length * 5 + 5;
      
      // Answer summary
      doc.setFont('helvetica', 'bold');
      doc.text('Answer Summary:', 20, yPos);
      
      doc.setFont('helvetica', 'normal');
      const answerSummary = qa.answer.substring(0, 150) + (qa.answer.length > 150 ? '...' : '');
      const answerLines = splitTextToLines(answerSummary, 150, doc);
      answerLines.forEach((line, lineIndex) => {
        doc.text(line, 30, yPos + 6 + (lineIndex * 5));
      });
      yPos += answerLines.length * 5 + 15;
      
      if (qa.score !== undefined) {
        doc.setFont('helvetica', 'bold');
        doc.text(`Score: ${qa.score}%`, 20, yPos - 5);
      }
    });
  }
  
  // Add footers to all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addPageFooter(doc, i, pageCount);
  }
  
  // Save the PDF
  const fileName = `${candidate.name.replace(/\s+/g, '_')}_Comprehensive_Interview_Report.pdf`;
  doc.save(fileName);
};
